[project]
name = "mm-madam-aws"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv",
    "google-genai",
    "fastapi",
    "uvicorn",
    "httpx",
    "pyjwt",
    "markdown",
    "markdownify",
    "gdown @ git+https://github.com/x1001000/gdown",
]
